masterpiece/canvas/urls.py
from django.urls import path

from . import views


app_name = 'canvas'

urlpatterns = [
    path('', views.CanvasView.as_view(), name='canvas'),
    path('pixels/', views.canvas_pixels, name='pixels'),
]

masterpiece/masterpiece/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


# customize admin site
admin.site.site_header = "Masterpiece Administration"
admin.site.site_title = "Masterpiece Admin"


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('canvas.urls', namespace='canvas')),
]


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

masterpiece/canvas/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


class Canvas(models.Model):
    name = models.CharField(max_length=100, unique=True)
    width = models.PositiveIntegerField()
    height = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Canvases"

    def __str__(self):
        return self.name


class Pixel(models.Model):
    canvas = models.ForeignKey(Canvas, on_delete=models.CASCADE)
    x = models.PositiveIntegerField()
    y = models.PositiveIntegerField()
    color = models.CharField(max_length=7, validators=[
                RegexValidator(r'#\d{6}', "Color must be in '#RRGGBB' format.")])
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "{}, {} on {}".format(self.x, self.y, str(self.canvas))

    def clean(self):
        validation_errors = {}

        if self.x >= self.canvas.width:
            validation_errors['x'] = f"X '{self.x}' is not on canvas with max x of '{self.canvas.width - 1}'."
        if self.y >= self.canvas.height:
            validation_errors['y'] = f"Y '{self.y}' is not on canvas with max y of '{self.canvas.height - 1}'."

        if len(validation_errors.keys()) > 0:
            raise ValidationError(validation_errors)

masterpiece/canvas/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_GET

from .models import Canvas, Pixel


class CanvasView(TemplateView):
    template_name = 'canvas/canvas.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        canvas, _ = Canvas.objects.get_or_create(
            name='Default Canvas',
            defaults={
                'width': 1920,
                'height': 1080,
            }
        )

        context['canvas'] = canvas

        return context


@require_GET
def canvas_pixels(request):
    canvas = get_object_or_404(Canvas, pk=request.GET.get('canvas'))

    return JsonResponse({
        'pixels': list(Pixel.objects.filter(
            canvas=canvas,
            active=True,
        ).values('x', 'y', 'color')),
    })

masterpiece/canvas/templates/canvas/base.html
<!DOCTYPE html> {% load static compress %}
<html>

<head>
  <meta charset="utf-8">

  <link rel="shortcut icon" type="image/png" href="{% static 'canvas/images/favicon.png' %}">

  <title>Masterpiece</title>

  {% compress css %}
    {% block styles %}{% endblock %}
  {% endcompress %}

  {% if google_analytics %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ google_analytics }}');
    </script>
  {% endif %}

  <!-- Developed by kjpc-tech (https://kjpc.tech/developerlink/) -->
</head>

<body>
  <main>
    {% block content %}{% endblock %}
  </main>

  {% compress js %}
    {% block scripts %}{% endblock %}
  {% endcompress %}
</body>

</html>

masterpiece/canvas/templates/canvas/canvas.html
{% extends "canvas/base.html" %}

{% load static %}

{% block styles %}
  <link href="{% static 'canvas/css/canvas.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

  <div id="holder" ref="holder">
    <canvas id="canvas" ref="canvas" width="{{ canvas.width }}" height="{{ canvas.height }}" v-on:click="color_pixel"></canvas>

    <div>
      <input ref="pixels_history" type="hidden" v-model="pixels_history" data-default="{% url 'canvas:pixels' %}">
      <input ref="canvas_id" type="hidden" v-model="canvas_id" data-default="{{ canvas.pk }}">
      <input ref="scheme" type="hidden" v-model="scheme" data-default="{{ request.scheme }}">
      <input id="color" ref="color" type="color" v-model="color" data-default="#000000">
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="{% static 'canvas/js/vue.min.js' %}"></script>
  <script src="{% static 'canvas/js/vue-resource.min.js' %}"></script>
  <script src="{% static 'canvas/js/canvas.js' %}"></script>
{% endblock %}